AWSTemplateFormatVersion: '2010-09-09'
Description: Template for describing resources related to application deployment

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: devq.iot.iot-platform
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
