AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS CloudFormation Template

Parameters: 
  Project:
    Type: String
    Description: Project name
    
Globals: 
  Function:
    Timeout: 10
    Runtime: python3.11
    CodeUri: ../src/
    MemorySize: 256
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Ref AWS::AccountId
        DYNAMO_REGION: !Ref AWS::Region
    
    
Resources:
    
  DeviceHandler:
    Type: AWS::Serverless::Function
    Properties: 
     FunctionName: !Sub "${Project}-Device"
     CodeUri: ../src/
     Handler: lambda.lambda_handler_Device
     Role:
       Fn::ImportValue: !Sub "${Project}-LambdaExecutionRoleArn"
     Tags:
        Name: !Sub "${Project}-Device"
        
          
  BuildingHandler:
    Type: AWS::Serverless::Function
    Properties: 
     FunctionName: !Sub "${Project}-Building"
     CodeUri: ../src/
     Handler: lambda.lambda_handler_Building
     Role:
       Fn::ImportValue: !Sub "${Project}-LambdaExecutionRoleArn"
     Tags:
        Name: !Sub "${Project}-Building"
        
          
  BuildingDeviceHandler:
    Type: AWS::Serverless::Function
    Properties: 
     FunctionName: !Sub "${Project}-BuildingDevice"
     CodeUri: ../src/
     Handler: lambda.lambda_handler_BuildingDevice
     Role:
       Fn::ImportValue: !Sub "${Project}-LambdaExecutionRoleArn"
     Tags:
        Name: !Sub "${Project}-BuildingDevice"
        
          
    
  IoTTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: IoT
      AttributeDefinitions: 
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes: 
        - IndexName: SK-PK
          KeySchema:  
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        
          
    
  GraphQLAPI:
    Type: AWS::Serverless::GraphQLApi
    Properties: 
      SchemaUri: ../src/graphql/schema.graphql
      Auth:
        Type: AMAZON_COGNITO_USER_POOLS
        UserPool: 
          AwsRegion: !Ref AWS::Region
          DefaultAction: ALLOW
          UserPoolId: 
            Fn::ImportValue: !Sub "${Project}-IoTApplicationUserPoolId" 
      DataSources:
        Lambda:
          LambdaDevice:
            Name: !Sub "${Project}_LambdaDevice"
            Description: Lambda DataSource
            FunctionArn: !GetAtt DeviceHandler.Arn
          LambdaBuilding:
            Name: !Sub "${Project}_LambdaBuilding"
            Description: Lambda DataSource
            FunctionArn: !GetAtt BuildingHandler.Arn
          LambdaBuildingDevice:
            Name: !Sub "${Project}_LambdaBuildingDevice"
            Description: Lambda DataSource
            FunctionArn: !GetAtt BuildingDeviceHandler.Arn
      Functions:
        lambdaInvokerDevice:
          CodeUri: ../src/graphql/invoker.js
          DataSource: LambdaDevice
          Description: Lambda invoker function
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
        lambdaInvokerBuilding:
          CodeUri: ../src/graphql/invoker.js
          DataSource: LambdaBuilding
          Description: Lambda invoker function
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
        lambdaInvokerBuildingDevice:
          CodeUri: ../src/graphql/invoker.js
          DataSource: LambdaBuildingDevice
          Description: Lambda invoker function
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
      Resolvers:
        Query:
          getDeviceById:
            Pipeline:
              - lambdaInvokerDevice
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          getDevices:
            Pipeline:
              - lambdaInvokerDevice
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          getBuildingById:
            Pipeline:
              - lambdaInvokerBuilding
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          getBuildings:
            Pipeline:
              - lambdaInvokerBuilding
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          getLinkBuildingDevice:
            Pipeline:
              - lambdaInvokerBuildingDevice
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
        Mutation:
          createDevice:
            Pipeline:
              - lambdaInvokerDevice
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          deleteDevice:
            Pipeline:
              - lambdaInvokerDevice
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          updateDevice:
            Pipeline:
              - lambdaInvokerDevice
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          createBuilding:
            Pipeline:
              - lambdaInvokerBuilding
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          deleteBuilding:
            Pipeline:
              - lambdaInvokerBuilding
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          updateBuilding:
            Pipeline:
              - lambdaInvokerBuilding
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          createLinkBuildingDevice:
            Pipeline:
              - lambdaInvokerBuildingDevice
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          deleteBuildingLinkDevice:
            Pipeline:
              - lambdaInvokerBuildingDevice
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
          updateLinkBuildingDevice:
            Pipeline:
              - lambdaInvokerBuildingDevice
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
    
    

Outputs:

  GraphQLAPIEndpoint:
    Description: GraphQLAPIEndpoint
    Value: !GetAtt GraphQLAPI.GraphQLUrl
    Export:
      Name: !Sub "${Project}-GraphQLAPIEndpoint" 
    