AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Generate template

# region parameters

Parameters:

  Project:
    Type: String
    Description: Project name

  S3Bucket:
    Type: String
    Description: S3 bucket name
    Default: devq.iot.iot-platform

  S3Folder:
    Type: String
    Description: S3 folder name
    Default: code_generated

# endregion

# region globals

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    CodeUri: ../src/
    MemorySize: 256
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Ref AWS::AccountId
        DYNAMO_REGION: !Ref AWS::Region

# endregion

Resources:

  ApplicationApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v2
      Name: !Sub "${Project}-ApplicationApiGateway"
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  DownloadZipCode:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Project}-DownloadZipCode"
      Description: Function to download zip file
      CodeUri: ../src/
      Handler: download_code.download_zip_code
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3Bucket
          FOLDER_NAME: !Ref S3Folder
      Tags:
        Name: !Sub "${Project}-DownloadZipCode"
      Events:
        DownloadZipCode:
          Type: Api
          Properties:
            RestApiId: !Ref ApplicationApiGateway
            Path: /download
            Method: GET


  # region Lambda functions roles and policies

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      RoleName: !Sub "${Project}-LambdaExecutionRole"
      AssumeRolePolicyDocument: !Sub "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  # Policy attached to Lambda functions runs

  LambdaExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${Project}-LambdaExecutionPolicy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "dynamodb:PutItem"
              - "dynamodb:DeleteItem"
              - "dynamodb:Scan"
              - "dynamodb:Query"
              - "dynamodb:UpdateItem"
              - "dynamodb:GetItem"
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/IoT"
          - Effect: Allow
            Action:
              - "s3:PutObject*"
              - "s3:GetObject*"
              - "s3:DeleteObject"
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}/*"
          - Effect: Allow
            Action:
              - "s3:ListBucket"
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}"
            Condition:
              StringLike:
                s3:prefix:
                  - !Sub "${S3Folder}"
      Roles:
        - !Ref LambdaExecutionRole

  # endregion

Outputs:

  APIGatewayId:
    Description: API gateway id
    Value: !Sub 'https://${ApplicationApiGateway}.execute-api.${AWS::Region}.amazonaws.com/v2/'
    Export:
      Name: !Sub "${Project}-ApiGatewayId"


  LambdaExecutionRole:
    Description: The ARN of the lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub "${Project}-LambdaExecutionRoleArn"



