AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Generate template

# region parameters

Parameters:

  Project:
    Type: String
    Description: Project name

  S3Bucket:
    Type: String
    Description: S3 bucket name

  s3Folder:
    Type: String
    Description: S3 folder name

# endregion

# region globals

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    CodeUri: ../src/
    MemorySize: 256
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Ref AWS::AccountId
        DYNAMO_REGION: !Ref AWS::Region
        S3_BUCKET: !Ref S3Bucket
        S3_FOLDER: !Ref s3Folder

# endregion

Resources:

  GetS3FolderUrl:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Project}-GetS3FolderUrl"
      Description: Test function to get S3 folder url
      CodeUri: src/Controller
      Handler: generate.lambda_handler
      Role:


        Fn::ImportValue: !Sub "${Project}-LambdaExecutionRoleArn"
      Environment:
        Variables:
          BUCKET_NAME: !Ref S3Bucket
          FOLDER_NAME: !Ref s3Folder


