AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for describing resources related to application deployment

# region parameters

Parameters:

  BucketName:
    Type: String
    Description: Name of the S3 bucket to create
    Default: devq.iot.iot-platform

  IdForDomain:
    Type: String
    Description: Id of the domain for the CloudFront distribution
    Default: S3-iot-platform.devq.it

# endregion

Resources:

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            Prefix: ""
            ExpirationInDays: 1
            TagFilters:
              - Key: file-type
                Value: zip

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${MyS3Bucket}/*"

  MyCloudFrontDistributionForRootDomain:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: !Ref IdForDomain
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !Sub '${MyS3Bucket}.s3-website.${AWS::Region}.amazonaws.com'
            Id: !Ref IdForDomain
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:

  outputCloudFrontDistributionForRootDomainId:
    Description: CloudFront distribution ID
    Value: !Ref MyCloudFrontDistributionForRootDomain

  outputCloudFrontDistributionDomainNameForRootDomain:
    Description: CloudFront distribution domain name
    Value: !GetAtt MyCloudFrontDistributionForRootDomain.DomainName