AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template to create GraphQL API

# region parameters

Parameters:

  Project:
    Type: String
    Description: Name of the project

# endregion

# region globals

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    CodeUri: ../src/
    MemorySize: 256
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Ref AWS::AccountId
        DYNAMO_REGION: !Ref AWS::Region

# endregion

Resources:

  GetDevice:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Project}-GetDevice"
      Description: Get device by id from DynamoDB table
      CodeUri: src/Controller
      Handler: controller.getDevice
      Role:
        Fn::ImportValue: !Sub "${Project}-LambdaExecutionRoleArn"


  GraphQLAPI:
    Type: AWS::Serverless::GraphQLApi
    Properties:
      Auth:
        Type: API_KEY  #IAM
      DataSources:
        Lambda:
          LambdaDataSource:
            Name: !Sub "${Project}_LambdaDataSource"
            Description: Lambda DataSource
            FunctionArn: !GetAtt GetDevice.Arn
      Functions:
        lambdaInvoker:
          CodeUri: src/invoker.js
          DataSource: LambdaDataSource
          Description: Lambda invoker function
          Runtime:
            Name: APPSYNC_JS
            Version: 1.0.0
      Resolvers:
        Query:
          getDevice:
            Pipeline:
              - lambdaInvoker
            Runtime:
              Name: APPSYNC_JS
              Version: 1.0.0
      SchemaUri: src/schema.graphql

Outputs:
  APIEndpoint:
    Description: AppSync GraphQL API endpoint
    Value: !GetAtt GraphQLAPI.GraphQLUrl



